[package]
name = "Rudy"
version = "0.1.0"
authors = ["Mike Lloyd <michael.lloyd03@github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version="0.2", features=["full"]}
tokio-native-tls="0.1.0"
bytes = "0.5"
url = "2.1.1"
indoc = "1.0"
native-tls="0.2.4"
openssl = "0.10.38"
openssl-sys = "0.9.72"
anyhow = "1.0.56"
