#!/bin/bash

if [ -f ca.crt ]; then
  echo "CA certificate already exists. Running this program will overwrite it."
  echo -n "Are you sure you want to do this? [y/N] "
  read -r input
  case $input in
  y | Y | yes) ;;
  *)
    echo "Aborting."
    exit 1
    ;;
  esac
fi

# Generate CA
openssl genrsa -out ca.key 4096
openssl req -x509 -new -sha512 -nodes -key ca.key -days 7307 -out ca.crt -config config/ca.conf
