name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: cargo build --release
    - name: make tarball
      run: mkdir rudy-linux && cp -r target/release/rudy cert README.md rudy-linux && tar -czf rudy-linux.tar.gz rudy-linux
    - name: upload tarball
      uses: actions/upload-artifact@v3
      with:
        name: uploads
        path: rudy-linux.tar.gz

  build-mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: cargo build --release
    - name: make zip
      run: mkdir rudy-mac && cp -r target/release/rudy cert README.md rudy-mac && zip -r rudy-mac.zip rudy-mac
    - name: upload zip
      uses: actions/upload-artifact@v3
      with:
        name: uploads
        path: rudy-mac.zip

  upload-to-release:
    runs-on: ubuntu-latest
    needs:
      - build-linux
      - build-mac
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: create release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: download artifacts
        id: download_artifacts
        uses: actions/download-artifact@v3
        with:
          name: uploads
          path: uploads

      - name: upload linux binary
        id: upload-linux
        uses: actions/upload-release-asset@v1.0.2
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.download_artifacts.outputs.download-path }}/rudy-linux.tar.gz
          asset_name: rudy-linux.tar.gz
          asset_content_type: application/gzip

      - name: upload mac binary
        id: upload-mac
        uses: actions/upload-release-asset@v1.0.2
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.download_artifacts.outputs.download-path }}/rudy-mac.zip
          asset_name: rudy-mac.zip
          asset_content_type: application/zip
